### ISSUE TITLE
issue 查询响应异常

### ISSUE THREAD

**Issue by duhaibo0404** [uxff/gohive#2]
执行hive 查询 数据超过100条，就会卡主很久很久 ，最后无法响应

**Comment by uxff** [comment]
hive版本，thrift版本对少？

**Comment by uxff** [comment]
> 执行hive 查询 数据超过100条，就会卡主很久很久 ，最后无法响应

hive版本，thrift版本多少？

**Comment by duhaibo0404** [comment]
hive版本是2.1 thrift-0.9.3

生产环境数据比较多 通过这个就有问题

**Comment by duhaibo0404** [comment]
转投 github.com/beltran/gohive 生产环境了

**Comment by uxff** [comment]
谢谢。
